//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.5485
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace CorpusExplorer.Sdk.Extern.Xml.AnnotationPro.Model
{ // 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=2.0.50727.3038.
// 


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [XmlType(AnonymousType=true, Namespace="http://tempuri.org/AnnotationSystemDataSet.xsd")]
  [XmlRoot(Namespace="http://tempuri.org/AnnotationSystemDataSet.xsd", IsNullable=false)]
  public partial class AnnotationSystemDataSet {
    
    private Layer[] layerField;
    
    private Segment[] segmentField;
    
    private AudioFile[] audioFileField;
    
    private Configuration[] configurationField;
    
    /// <remarks/>
    [XmlElement("Layer")]
    public Layer[] Layer {
      get {
        return this.layerField;
      }
      set {
        this.layerField = value;
      }
    }
    
    /// <remarks/>
    [XmlElement("Segment")]
    public Segment[] Segment {
      get {
        return this.segmentField;
      }
      set {
        this.segmentField = value;
      }
    }
    
    /// <remarks/>
    [XmlElement("AudioFile")]
    public AudioFile[] AudioFile {
      get {
        return this.audioFileField;
      }
      set {
        this.audioFileField = value;
      }
    }
    
    /// <remarks/>
    [XmlElement("Configuration")]
    public Configuration[] Configuration {
      get {
        return this.configurationField;
      }
      set {
        this.configurationField = value;
      }
    }
  }
}