//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 
namespace CorpusExplorer.Sdk.Extern.Xml.Ids.Model
{

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class idsCorpus
  {

    private idsHeader idsHeaderField;

    private idsDoc[] idsDocField;

    private string tEIformField;

    private decimal versionField;

    /// <remarks/>
    public idsHeader idsHeader
    {
      get { return this.idsHeaderField; }
      set { this.idsHeaderField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("idsDoc")]
    public idsDoc[] idsDoc
    {
      get { return this.idsDocField; }
      set { this.idsDocField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NCName")]
    public string TEIform
    {
      get { return this.tEIformField; }
      set { this.tEIformField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version
    {
      get { return this.versionField; }
      set { this.versionField = value; }
    }
  }
}