//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpusExplorer.Sdk.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CorpusExplorer.Sdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Dokumente von ähnelt.
        /// </summary>
        internal static string AllDocumentsFrom {
            get {
                return ResourceManager.GetString("AllDocumentsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Werte in einem Dokument ({0}). ähnelt.
        /// </summary>
        internal static string AllValues {
            get {
                return ResourceManager.GetString("AllValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Werte in einem Satz ({0}). ähnelt.
        /// </summary>
        internal static string AllValuesInOneSentence {
            get {
                return ResourceManager.GetString("AllValuesInOneSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Werte ({0}) mit einem Abstand von {1} Sätzen. ähnelt.
        /// </summary>
        internal static string AllValuesWithSentenceSpace {
            get {
                return ResourceManager.GetString("AllValuesWithSentenceSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Werte ({0}) mit einem Abstand von {1} Worten. ähnelt.
        /// </summary>
        internal static string AlLValuesWithWordSpace {
            get {
                return ResourceManager.GetString("AlLValuesWithWordSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie ähnelt.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die categoryA ähnelt.
        /// </summary>
        internal static string CategoryA {
            get {
                return ResourceManager.GetString("CategoryA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die categoryB ähnelt.
        /// </summary>
        internal static string CategoryB {
            get {
                return ResourceManager.GetString("CategoryB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chi-Quadrat-Test (CQT) ähnelt.
        /// </summary>
        internal static string ChiQuadratTestCQT {
            get {
                return ResourceManager.GetString("ChiQuadratTestCQT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Komplexität ähnelt.
        /// </summary>
        internal static string Complexity {
            get {
                return ResourceManager.GetString("Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If the value of sentenceStopIndex or wordStopIndex is greater than -1, then you must also set the other value. ähnelt.
        /// </summary>
        internal static string ConceptRangeException {
            get {
                return ResourceManager.GetString("ConceptRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kookkurrenz ähnelt.
        /// </summary>
        internal static string Cooccurrence {
            get {
                return ResourceManager.GetString("Cooccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extreme Bereinigung für Korpora mit großer Wertvarianz ähnelt.
        /// </summary>
        internal static string CorpusCleanup {
            get {
                return ResourceManager.GetString("CorpusCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Korpusverteilung ähnelt.
        /// </summary>
        internal static string CorpusDistribution {
            get {
                return ResourceManager.GetString("CorpusDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellt ähnelt.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kreuz-Frequenz ähnelt.
        /// </summary>
        internal static string CrossFrequency {
            get {
                return ResourceManager.GetString("CrossFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yyyy-MM-dd HH-mm ähnelt.
        /// </summary>
        internal static string DateTimeFormat_Long {
            get {
                return ResourceManager.GetString("DateTimeFormat_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yy-MMM-dd HH:mm:ss ähnelt.
        /// </summary>
        internal static string DateTimeFormat_Short {
            get {
                return ResourceManager.GetString("DateTimeFormat_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wortschatzkomplexität ähnelt.
        /// </summary>
        internal static string DictionaryComplexity {
            get {
                return ResourceManager.GetString("DictionaryComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source directory does not exist or could not be found: ähnelt.
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disambiguierung ähnelt.
        /// </summary>
        internal static string Disambigution {
            get {
                return ResourceManager.GetString("Disambigution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verteilung in allen Sätzen ähnelt.
        /// </summary>
        internal static string DistributionOverSentences {
            get {
                return ResourceManager.GetString("DistributionOverSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokument ähnelt.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumenteninhalt ähnelt.
        /// </summary>
        internal static string DocumentContent {
            get {
                return ResourceManager.GetString("DocumentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verteilung in allen Dokumenten ähnelt.
        /// </summary>
        internal static string DocumentDistribution {
            get {
                return ResourceManager.GetString("DocumentDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokument-Metadaten ähnelt.
        /// </summary>
        internal static string DocumentMeta {
            get {
                return ResourceManager.GetString("DocumentMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumente ähnelt.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumentenähnlichkeit ähnelt.
        /// </summary>
        internal static string DocumentSimilarity {
            get {
                return ResourceManager.GetString("DocumentSimilarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumentengröße ähnelt.
        /// </summary>
        internal static string DocumentSize {
            get {
                return ResourceManager.GetString("DocumentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumente (1) ähnelt.
        /// </summary>
        internal static string Dokumente1 {
            get {
                return ResourceManager.GetString("Dokumente1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumente (2) ähnelt.
        /// </summary>
        internal static string Dokumente2 {
            get {
                return ResourceManager.GetString("Dokumente2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumente D(1, 2) ähnelt.
        /// </summary>
        internal static string DokumenteD12 {
            get {
                return ResourceManager.GetString("DokumenteD12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokument (GUID) ähnelt.
        /// </summary>
        internal static string DokumentGUID {
            get {
                return ResourceManager.GetString("DokumentGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokument-Metadaten {0} = {1} ähnelt.
        /// </summary>
        internal static string DokumentMetadaten01 {
            get {
                return ResourceManager.GetString("DokumentMetadaten01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokument-Metadaten (exakt) {0} = {1} ähnelt.
        /// </summary>
        internal static string DokumentMetadatenExakt01 {
            get {
                return ResourceManager.GetString("DokumentMetadatenExakt01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finde korrespondierende Werte ähnelt.
        /// </summary>
        internal static string FindCorrespondingValues {
            get {
                return ResourceManager.GetString("FindCorrespondingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequenz ähnelt.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequenz (relativ) ähnelt.
        /// </summary>
        internal static string Frequency_Relativ {
            get {
                return ResourceManager.GetString("Frequency_Relativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequenz (individueller Layer) ähnelt.
        /// </summary>
        internal static string FrequencyOnSpecialLayer {
            get {
                return ResourceManager.GetString("FrequencyOnSpecialLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequenz (1) ähnelt.
        /// </summary>
        internal static string Frequeny1 {
            get {
                return ResourceManager.GetString("Frequeny1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequenz (2) ähnelt.
        /// </summary>
        internal static string Frequeny2 {
            get {
                return ResourceManager.GetString("Frequeny2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequenz D(1, 2) ähnelt.
        /// </summary>
        internal static string FrequenyD12 {
            get {
                return ResourceManager.GetString("FrequenyD12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volltextsuche ähnelt.
        /// </summary>
        internal static string FulltextSearch {
            get {
                return ResourceManager.GetString("FulltextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppe ähnelt.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppiere Dokumente nach Datum ähnelt.
        /// </summary>
        internal static string GroupDocumentsByDate {
            get {
                return ResourceManager.GetString("GroupDocumentsByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppiere Dokumente nach einer Metaangabe ähnelt.
        /// </summary>
        internal static string GroupDocumentsByMeta {
            get {
                return ResourceManager.GetString("GroupDocumentsByMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identische Sätze ähnelt.
        /// </summary>
        internal static string IdenticalSentences {
            get {
                return ResourceManager.GetString("IdenticalSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index ähnelt.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keywords ähnelt.
        /// </summary>
        internal static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezeichnung ähnelt.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more Layer in the parameter layers are null ähnelt.
        /// </summary>
        internal static string LayerValueNullError {
            get {
                return ResourceManager.GetString("LayerValueNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequenz Links/Rechts ähnelt.
        /// </summary>
        internal static string LeftRightFrequency {
            get {
                return ResourceManager.GetString("LeftRightFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lemma (Grundform) ähnelt.
        /// </summary>
        internal static string LemmaLongLabel {
            get {
                return ResourceManager.GetString("LemmaLongLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log-Likelihood-Test (LLT) ähnelt.
        /// </summary>
        internal static string LogLikelihoodTestLLT {
            get {
                return ResourceManager.GetString("LogLikelihoodTestLLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measure ähnelt.
        /// </summary>
        internal static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metadaten ähnelt.
        /// </summary>
        internal static string MetadataLabel {
            get {
                return ResourceManager.GetString("MetadataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ eines einmal gesetzten Typs kann nachträglich nicht verändert werden (Typsicherheit). ähnelt.
        /// </summary>
        internal static string MetaDataTypeExcetion {
            get {
                return ResourceManager.GetString("MetaDataTypeExcetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Parameter ist keine gültige Metaangabe ähnelt.
        /// </summary>
        internal static string MetaErrorNoValidValue {
            get {
                return ResourceManager.GetString("MetaErrorNoValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mehrworteinheiten auszählen ähnelt.
        /// </summary>
        internal static string MultiwordFrequency {
            get {
                return ResourceManager.GetString("MultiwordFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meine Korpora ähnelt.
        /// </summary>
        internal static string MyCorpora {
            get {
                return ResourceManager.GetString("MyCorpora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meine Datenquellen ähnelt.
        /// </summary>
        internal static string MyDataSources {
            get {
                return ResourceManager.GetString("MyDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meine Erweiterungen ähnelt.
        /// </summary>
        internal static string MyExtension {
            get {
                return ResourceManager.GetString("MyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meine Projekte ähnelt.
        /// </summary>
        internal static string MyProjects {
            get {
                return ResourceManager.GetString("MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N ähnelt.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitung ähnelt.
        /// </summary>
        internal static string Newspaper {
            get {
                return ResourceManager.GetString("Newspaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N-Gramm ähnelt.
        /// </summary>
        internal static string NGram {
            get {
                return ResourceManager.GetString("NGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -KEINE DATEN- ähnelt.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Titel (GUID: {0}) ähnelt.
        /// </summary>
        internal static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partner ähnelt.
        /// </summary>
        internal static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Muster ähnelt.
        /// </summary>
        internal static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Poisson-Verteilung (PV) ähnelt.
        /// </summary>
        internal static string PoissonVerteilungPV {
            get {
                return ResourceManager.GetString("PoissonVerteilungPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Part-of-Speech (POS) ähnelt.
        /// </summary>
        internal static string POSLongLabel {
            get {
                return ResourceManager.GetString("POSLongLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt ähnelt.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abfrage ähnelt.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lesbarkeit ähnelt.
        /// </summary>
        internal static string ReadingEase {
            get {
                return ResourceManager.GetString("ReadingEase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche nach der Phrase ({0}). ähnelt.
        /// </summary>
        internal static string SearchForPhrases {
            get {
                return ResourceManager.GetString("SearchForPhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schnappschuss-Zufallsgenerator (Split) ähnelt.
        /// </summary>
        internal static string SelectionRandimSplit {
            get {
                return ResourceManager.GetString("SelectionRandimSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zufallsauswahl (Split-A): {0}% ähnelt.
        /// </summary>
        internal static string SelectionRandimSplitA {
            get {
                return ResourceManager.GetString("SelectionRandimSplitA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zufallsauswahl (Split-B): {0}% ähnelt.
        /// </summary>
        internal static string SelectionRandimSplitB {
            get {
                return ResourceManager.GetString("SelectionRandimSplitB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zufällige Auswahl von {0} Dokumenten ({1}%) ähnelt.
        /// </summary>
        internal static string SelectionRandomDescribtion {
            get {
                return ResourceManager.GetString("SelectionRandomDescribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Funktion SetNewDocumentMetadata(string metadataKey, object defaultValue) erwartet für den Parameter &quot;defaultValue&quot; einen als serialisierbar gekennzeichneten Wert. Bitte kennzeichnen Sie den Typ des Werts ({0}) als serialisierbar. ähnelt.
        /// </summary>
        internal static string SetDocumentMetadata_SerializerException {
            get {
                return ResourceManager.GetString("SetDocumentMetadata_SerializerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signifikanz ähnelt.
        /// </summary>
        internal static string Significance {
            get {
                return ResourceManager.GetString("Significance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signifikanz (1) ähnelt.
        /// </summary>
        internal static string Significance1 {
            get {
                return ResourceManager.GetString("Significance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signifikanz (2) ähnelt.
        /// </summary>
        internal static string Significance2 {
            get {
                return ResourceManager.GetString("Significance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signifikanz D(1, 2) ähnelt.
        /// </summary>
        internal static string SignificanceD12 {
            get {
                return ResourceManager.GetString("SignificanceD12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silben ähnelt.
        /// </summary>
        internal static string Silben {
            get {
                return ResourceManager.GetString("Silben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standardbereinigung ähnelt.
        /// </summary>
        internal static string StandardCleanup {
            get {
                return ResourceManager.GetString("StandardCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeichenkette ähnelt.
        /// </summary>
        internal static string StringLabel {
            get {
                return ResourceManager.GetString("StringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeichenkette (Wortform) ähnelt.
        /// </summary>
        internal static string StringLabelLong {
            get {
                return ResourceManager.GetString("StringLabelLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temporäre Auswahl ähnelt.
        /// </summary>
        internal static string TemporarySelection {
            get {
                return ResourceManager.GetString("TemporarySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Token ähnelt.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Token (1) ähnelt.
        /// </summary>
        internal static string Token1 {
            get {
                return ResourceManager.GetString("Token1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Token (2) ähnelt.
        /// </summary>
        internal static string Token2 {
            get {
                return ResourceManager.GetString("Token2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Token D(1, 2) ähnelt.
        /// </summary>
        internal static string TokenD12 {
            get {
                return ResourceManager.GetString("TokenD12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Types ähnelt.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Types (1) ähnelt.
        /// </summary>
        internal static string Types1 {
            get {
                return ResourceManager.GetString("Types1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Types (2) ähnelt.
        /// </summary>
        internal static string Types2 {
            get {
                return ResourceManager.GetString("Types2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Types D(1, 2) ähnelt.
        /// </summary>
        internal static string TypesD12 {
            get {
                return ResourceManager.GetString("TypesD12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einheit ähnelt.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eigenschaft Path darf bei virtuellen Korpora nicht null sein. Bitte verwenden Sie zum laden des Korpus die statische Funktion Corpora.Load(string path); ähnelt.
        /// </summary>
        internal static string VirtualCorpusNullPathException {
            get {
                return ResourceManager.GetString("VirtualCorpusNullPathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert ähnelt.
        /// </summary>
        internal static string Wert {
            get {
                return ResourceManager.GetString("Wert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert (1) ähnelt.
        /// </summary>
        internal static string Wert1 {
            get {
                return ResourceManager.GetString("Wert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert (2) ähnelt.
        /// </summary>
        internal static string Wert2 {
            get {
                return ResourceManager.GetString("Wert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert D(1, 2) ähnelt.
        /// </summary>
        internal static string WertD12 {
            get {
                return ResourceManager.GetString("WertD12", resourceCulture);
            }
        }
    }
}
