#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CorpusExplorer.Sdk.Db.QuickSearchDb;

namespace CorpusExplorer.Sdk.Db.QuickSearchDb	
{
	public partial class TermMetadata
	{
		private ulong _id;
		public virtual ulong Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _key;
		public virtual string Key
		{
			get
			{
				return this._key;
			}
			set
			{
				this._key = value;
			}
		}
		
		private string _value;
		public virtual string Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		
		private Term _term;
		public virtual Term Term
		{
			get
			{
				return this._term;
			}
			set
			{
				this._term = value;
			}
		}
		
	}
}
#pragma warning restore 1591
