//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 

namespace CorpusExplorer.Sdk.Extern.Xml.Folker.Fln.Model
{
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute("folker-transcription", Namespace = "", IsNullable = false)]
  public partial class folkertranscription
  {

    private head headField;

    private speaker[] speakersField;

    private recording recordingField;

    private timepoint[] timelineField;

    private contribution[] contributionField;

    private string corpusdgdidField;

    private string dgdidField;

    private string idField;

    /// <remarks/>
    public head head
    {
      get { return this.headField; }
      set { this.headField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("speaker", IsNullable = false)]
    public speaker[] speakers
    {
      get { return this.speakersField; }
      set { this.speakersField = value; }
    }

    /// <remarks/>
    public recording recording
    {
      get { return this.recordingField; }
      set { this.recordingField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("timepoint", IsNullable = false)]
    public timepoint[] timeline
    {
      get { return this.timelineField; }
      set { this.timelineField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contribution")]
    public contribution[] contribution
    {
      get { return this.contributionField; }
      set { this.contributionField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("corpus-dgd-id", DataType = "NCName")]
    public string corpusdgdid
    {
      get { return this.corpusdgdidField; }
      set { this.corpusdgdidField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("dgd-id", DataType = "NCName")]
    public string dgdid
    {
      get { return this.dgdidField; }
      set { this.dgdidField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
      get { return this.idField; }
      set { this.idField = value; }
    }
  }
}