//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 

namespace CorpusExplorer.Sdk.Extern.Xml.Elan.Model
{

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class ANNOTATION_DOCUMENT
  {

    private HEADER hEADERField;

    private TIME_SLOT[] tIME_ORDERField;

    private TIER[] tIERField;

    private LINGUISTIC_TYPE[] lINGUISTIC_TYPEField;

    private LOCALE lOCALEField;

    private CONSTRAINT[] cONSTRAINTField;

    private string aUTHORField;

    private System.DateTime dATEField;

    private decimal fORMATField;

    private decimal vERSIONField;

    private string noNamespaceSchemaLocationField;

    /// <remarks/>
    public HEADER HEADER
    {
      get { return this.hEADERField; }
      set { this.hEADERField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("TIME_SLOT", IsNullable = false)]
    public TIME_SLOT[] TIME_ORDER
    {
      get { return this.tIME_ORDERField; }
      set { this.tIME_ORDERField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TIER")]
    public TIER[] TIER
    {
      get { return this.tIERField; }
      set { this.tIERField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LINGUISTIC_TYPE")]
    public LINGUISTIC_TYPE[] LINGUISTIC_TYPE
    {
      get { return this.lINGUISTIC_TYPEField; }
      set { this.lINGUISTIC_TYPEField = value; }
    }

    /// <remarks/>
    public LOCALE LOCALE
    {
      get { return this.lOCALEField; }
      set { this.lOCALEField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CONSTRAINT")]
    public CONSTRAINT[] CONSTRAINT
    {
      get { return this.cONSTRAINTField; }
      set { this.cONSTRAINTField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AUTHOR
    {
      get { return this.aUTHORField; }
      set { this.aUTHORField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime DATE
    {
      get { return this.dATEField; }
      set { this.dATEField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal FORMAT
    {
      get { return this.fORMATField; }
      set { this.fORMATField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal VERSION
    {
      get { return this.vERSIONField; }
      set { this.vERSIONField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string noNamespaceSchemaLocation
    {
      get { return this.noNamespaceSchemaLocationField; }
      set { this.noNamespaceSchemaLocationField = value; }
    }
  }
}