// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CorpusExplorer.Sdk.Extern.Json.TwitterStatus.Model
{

    public class Coordinates
    {

        [JsonProperty("Type")]
        public object Type { get; set; }

        [JsonProperty("Latitude")]
        public double Latitude { get; set; }

        [JsonProperty("Longitude")]
        public double Longitude { get; set; }

        [JsonProperty("IsLocationAvailable")]
        public bool IsLocationAvailable { get; set; }
    }

}
