// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CorpusExplorer.Sdk.Extern.Json.TwitterStatus.Model
{

    public class Size
    {

        [JsonProperty("Type")]
        public string Type { get; set; }

        [JsonProperty("Width")]
        public ulong Width { get; set; }

        [JsonProperty("Height")]
        public ulong Height { get; set; }

        [JsonProperty("Resize")]
        public string Resize { get; set; }
    }

}
