// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CorpusExplorer.Sdk.Extern.Json.TwitterStatus.Model
{

    public class UrlEntity
    {

        [JsonProperty("Url")]
        public string Url { get; set; }

        [JsonProperty("DisplayUrl")]
        public string DisplayUrl { get; set; }

        [JsonProperty("ExpandedUrl")]
        public string ExpandedUrl { get; set; }

        [JsonProperty("Start")]
        public ulong Start { get; set; }

        [JsonProperty("End")]
        public ulong End { get; set; }
    }

}
