//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 

namespace CorpusExplorer.Sdk.Extern.Xml.AltoXml._1._2.Model
{

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class alto
  {

    private Description descriptionField;

    private Styles stylesField;

    private Layout layoutField;

    private string noNamespaceSchemaLocationField;

    /// <remarks/>
    public Description Description
    {
      get { return this.descriptionField; }
      set { this.descriptionField = value; }
    }

    /// <remarks/>
    public Styles Styles
    {
      get { return this.stylesField; }
      set { this.stylesField = value; }
    }

    /// <remarks/>
    public Layout Layout
    {
      get { return this.layoutField; }
      set { this.layoutField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string noNamespaceSchemaLocation
    {
      get { return this.noNamespaceSchemaLocationField; }
      set { this.noNamespaceSchemaLocationField = value; }
    }
  }
}