#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CorpusExplorer.Sdk.Db.CorpusDb	
{
	public partial class DocumentMetadata
	{
		private ulong _documentId;
		public virtual ulong DocumentId
		{
			get
			{
				return this._documentId;
			}
			set
			{
				this._documentId = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _value;
		public virtual string Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		
		private Document _document;
		public virtual Document Document
		{
			get
			{
				return this._document;
			}
			set
			{
				this._document = value;
			}
		}
		
	}
}
#pragma warning restore 1591
