#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace CorpusExplorer.Sdk.Db.CorpusDb	
{
	public partial class Layer
	{
		private ulong _id;
		public virtual ulong Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private Corpus _corpus;
		public virtual Corpus Corpus
		{
			get
			{
				return this._corpus;
			}
			set
			{
				this._corpus = value;
			}
		}
		
		private IList<DocumentLayerIndex> _documentLayerIndices = new List<DocumentLayerIndex>();
		public virtual IList<DocumentLayerIndex> DocumentLayerIndices
		{
			get
			{
				return this._documentLayerIndices;
			}
		}
		
		private IList<LayerIndex> _layerIndices = new List<LayerIndex>();
		public virtual IList<LayerIndex> LayerIndices
		{
			get
			{
				return this._layerIndices;
			}
		}
		
	}
}
#pragma warning restore 1591
