#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace CorpusExplorer.Sdk.Db.CorpusDb	
{
	public partial class LayerIndex
	{
		private ulong _layerId;
		public virtual ulong LayerId
		{
			get
			{
				return this._layerId;
			}
			set
			{
				this._layerId = value;
			}
		}
		
		private ulong _index;
		public virtual ulong Index
		{
			get
			{
				return this._index;
			}
			set
			{
				this._index = value;
			}
		}
		
		private string _value;
		public virtual string Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		
		private Layer _layer;
		public virtual Layer Layer
		{
			get
			{
				return this._layer;
			}
			set
			{
				this._layer = value;
			}
		}
		
		private IList<DocumentLayerIndex> _documentLayerIndices = new List<DocumentLayerIndex>();
		public virtual IList<DocumentLayerIndex> DocumentLayerIndices
		{
			get
			{
				return this._documentLayerIndices;
			}
		}
		
	}
}
#pragma warning restore 1591
