//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpusExplorer.Installer.Sdk.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CorpusExplorer.Installer.Sdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überprüfe ob Programm- und/oder Korpusaktualisierungen verfügbar sind... ähnelt.
        /// </summary>
        internal static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei der Installation/Update ist ein Fehler aufgetreten. Dieser kann wie folgt behoben werden:
        ///
        ///1) Überprüfen Sie ihre Internetverbindung
        ///2) Starten Sie den CorpusExplorer erneut
        ///3) Der CorpusExplorer wird komplett neu installiert &amp; konfiguriert.
        ///
        ///Sollte der Fehler trotzdem weiterhin bestehen, kontaktieren Sie den Support: support@corpusexplorer.de ähnelt.
        /// </summary>
        internal static string CorpusExplorerBootstraper_InstallationUpdateErrorHelp {
            get {
                return ResourceManager.GetString("CorpusExplorerBootstraper_InstallationUpdateErrorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CorpusExplorer - Installation ähnelt.
        /// </summary>
        internal static string CorpusExplorerInstallation {
            get {
                return ResourceManager.GetString("CorpusExplorerInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CorpusExplorer\Meine Erweiterungen ähnelt.
        /// </summary>
        internal static string CorpusExplorerMyAddons {
            get {
                return ResourceManager.GetString("CorpusExplorerMyAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CorpusExplorer\Meine Korpora\ ähnelt.
        /// </summary>
        internal static string CorpusExplorerMyCorpora {
            get {
                return ResourceManager.GetString("CorpusExplorerMyCorpora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CorpusExplorer\Meine Datenquellen\ ähnelt.
        /// </summary>
        internal static string CorpusExplorerMyDataSources {
            get {
                return ResourceManager.GetString("CorpusExplorerMyDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CorpusExplorer\Meine Projekte\ ähnelt.
        /// </summary>
        internal static string CorpusExplorerMyProjects {
            get {
                return ResourceManager.GetString("CorpusExplorerMyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installieren ähnelt.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Installation läuft, bitte haben Sie einen Moment Geduld... ähnelt.
        /// </summary>
        internal static string InstallationIsRunningPleaseBePatient {
            get {
                return ResourceManager.GetString("InstallationIsRunningPleaseBePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinweis zu den Lizenzbedingungen: ähnelt.
        /// </summary>
        internal static string LicenceInformation {
            get {
                return ResourceManager.GetString("LicenceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie die Installation wirklich abbrechen? ähnelt.
        /// </summary>
        internal static string MainForm_AskAbortInstallation {
            get {
                return ResourceManager.GetString("MainForm_AskAbortInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie die Installation wirklich abbrechen? ähnelt.
        /// </summary>
        internal static string MainForm_AskAbortInstallation_Möchten_Sie_die_Installation_wirklich_abbrechen_ {
            get {
                return ResourceManager.GetString("MainForm_AskAbortInstallation_Möchten_Sie_die_Installation_wirklich_abbrechen_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation abbrechen? ähnelt.
        /// </summary>
        internal static string MainForm_AskAbortInstallationHeader {
            get {
                return ResourceManager.GetString("MainForm_AskAbortInstallationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte warten Installation / Update läuft... ähnelt.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shipment {
            get {
                object obj = ResourceManager.GetObject("shipment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Korpuslinguistik war nie so einfach... ähnelt.
        /// </summary>
        internal static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update abgeschlossen... ähnelt.
        /// </summary>
        internal static string UpdateCompleted {
            get {
                return ResourceManager.GetString("UpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Aktualisierung läuft, bitte haben Sie einen Moment Geduld... ähnelt.
        /// </summary>
        internal static string UpdateIsRunningPleaseBePatient {
            get {
                return ResourceManager.GetString("UpdateIsRunningPleaseBePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja, ich akzeptiere die Lizenzbedingungen ähnelt.
        /// </summary>
        internal static string YesIAcceptTheLicence {
            get {
                return ResourceManager.GetString("YesIAcceptTheLicence", resourceCulture);
            }
        }
    }
}
