//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 

namespace CorpusExplorer.Sdk.Extern.Xml.Gate.Model
{
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class GateDocument
  {

    private Feature[] gateDocumentFeaturesField;

    private TextWithNodes textWithNodesField;

    private AnnotationSet[] annotationSetField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Feature", IsNullable = false)]
    public Feature[] GateDocumentFeatures
    {
      get { return this.gateDocumentFeaturesField; }
      set { this.gateDocumentFeaturesField = value; }
    }

    /// <remarks/>
    public TextWithNodes TextWithNodes
    {
      get { return this.textWithNodesField; }
      set { this.textWithNodesField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnnotationSet")]
    public AnnotationSet[] AnnotationSet
    {
      get { return this.annotationSetField; }
      set { this.annotationSetField = value; }
    }
  }
}