<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.9" />
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
    <PackageReference Include="System.Text.Encodings.Web" Version="10.0.9" />
    <PackageReference Include="System.Text.Json" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="C:\Projekte-Kooperation\TfresWebserver\TefresWebserver\TFRES.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="credential.key">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="scopes.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
