namespace CorpusExplorer.Sdk.Properties
{
  public static class Resources
  {
    public static string LogLikelihoodTestLLT { get; } = "Log-Likelihood-Test (LLT)";
    public static string ChiQuadratTestCQT { get; } = "Chi-Quadrat-Test (CQT)";
    public static string PoissonVerteilungPV { get; } = "";
    public static string Newspaper { get; } = "Zeitung";
    public static string CategoryA { get; } = "categoryA";
    public static string CategoryB { get; } = "categoryB";
    public static string MetaErrorNoValidValue { get; } = "Der Parameter ist keine gültige Metaangabe";
    public static string NoData { get; } = "-KEINE DATEN-";
    public static string SelectionRandomDescription { get; } = "Zufällige Auswahl von {0} Dokumenten ({1}%)";
    public static string SelectionRandimSplitA { get; } = "Zufallsauswahl (Split-A): {0}%";
    public static string SelectionRandimSplitB { get; } = "Zufallsauswahl (Split-B): {0}%";
    public static string DirectoryNotFound { get; } = "Source directory does not exist or could not be found:";
    public static string MyCorpora { get; } = "Meine Korpora";
    public static string MyExtension { get; } = "Meine Erweiterungen";
    public static string MyDataSources { get; } = "Meine Datenquellen";
    public static string MyProjects { get; } = "Meine Projekte";
    public static string LayerValueNullError { get; } = "One or more Layer in the parameter layers are null";
    public static string MetaDataTypeExcetion { get; } = "Der Typ eines einmal gesetzten Typs kann nachträglich nicht verändert werden (Typsicherheit).";
    public static string N { get; } = "N";
    public static string Title { get; } = "Titel";
    public static string Project { get; } = "Projekt";
    public static string DateTimeFormat_Long { get; } = "yyyy-MM-dd HH-mm";
    public static string Created { get; } = "Erstellt";
    public static string Label { get; } = "Bezeichnung";
    public static string TemporarySelection { get; } = "Temporäre Auswahl";
    public static string AllDocumentsFrom { get; } = "Alle Dokumente von";
    public static string ConceptRangeException { get; } = "If the value of sentenceStopIndex or wordStopIndex is greater than -1, then you must also set the other value.";
    public static string Measure { get; } = "Measure";
    public static string Frequeny1 { get; } = "Frequenz (1)";
    public static string Frequeny2 { get; } = "Frequenz (2)";
    public static string FrequenyD12 { get; } = "Frequenz D(1, 2)";
    public static string Significance { get; } = "Signifikanz";
    public static string Frequency { get; } = "Frequenz";
    public static string NGram { get; } = "N-Gram";
    public static string DokumentMetadaten01 { get; } = "Dokument-Metadaten {0} = {1}";
    public static string DokumentMetadatenExakt01 { get; } = "Dokument-Metadaten (exakt) {0} = {1}";
    public static string AllValues { get; } = "Alle Werte in einem Dokument ({0}).";
    public static string AlLValuesWithWordSpace { get; } = "Alle Werte ({0}) mit einem Abstand von {1} Worten.";
    public static string AllValuesInOneSentence { get; } = "Alle Werte in einem Satz ({0}).";
    public static string StringLabel { get; } = "Zeichenkette";
    public static string Cooccurrence { get; } = "Kookkurrenz";
    public static string Significance1 { get; } = "Signifikanz (1)";
    public static string Significance2 { get; } = "Signifikanz (2)";
    public static string SignificanceD12 { get; } = "Signifikanz D(1, 2)";
    public static string Token { get; } = "Token";
    public static string Types { get; } = "Types";
    public static string Documents { get; } = "Dokumente";
    public static string MetadataLabel { get; } = "Metadaten";
    public static string Category { get; } = "Kategorie";
    public static string Token1 { get; } = "Token (1)";
    public static string Token2 { get; } = "Token (2)";
    public static string TokenD12 { get; } = "Token D(1, 2)";
    public static string Types1 { get; } = "Types (1)";
    public static string Types2 { get; } = "Types (2)";
    public static string TypesD12 { get; } = "Types D(1, 2)";
    public static string Dokumente1 { get; } = "Dokumente (1)";
    public static string Dokumente2 { get; } = "Dokumente (2)";
    public static string DokumenteD12 { get; } = "Dokumente (1, 2)";
    public static string Wert { get; } = "Wert";
    public static string Wert1 { get; } = "Wert (1)";
    public static string Wert2 { get; } = "Wert (2)";
    public static string WertD12 { get; } = "Wert D(1, 2)";
    public static string Frequency_Relativ { get; } = "Frequenz (relativ)";
    public static string SearchForPhrases { get; } = "Suche nach der Phrase ({0}).";
    public static string Unit { get; } = "Einheit";
    public static string Query { get; } = "Abfrage";
    public static string Group { get; } = "Gruppe";
    public static string Pattern { get; } = "Muster";
    public static string Index { get; } = "Index";
    public static string Partner { get; } = "Partner";
    public static string AllValuesWithSentenceSpace { get; } = "Alle Werte ({0}) mit einem Abstand von {1} Sätzen.";
    public static string CorpusCleanup { get; } = "Extreme Bereinigung für Korpora mit großer Wertvarianz";
    public static string StandardCleanup { get; } = "Standardbereinigung";
    public static string DocumentSimilarity { get; } = "Dokumentenähnlichkeit";
    public static string relativ { get; } = " (relativ)";
    public static string DokumentGUID { get; } = "Dokument (GUID)";
  }
}
