//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 
namespace CorpusExplorer.Sdk.Extern.Xml.BundestagOpenAccess.Plenarprotokolle.Model
{

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [XmlType(AnonymousType = true)]
  [XmlRoot(Namespace = "", IsNullable = false)]
  public partial class DOKUMENT
  {

    private string wAHLPERIODEField;

    private string dOKUMENTARTField;

    private string nrField;

    private string dATUMField;

    private string tITELField;

    private string tEXTField;

    /// <remarks/>
    [XmlElement(DataType = "integer")]
    public string WAHLPERIODE
    {
      get { return this.wAHLPERIODEField; }
      set { this.wAHLPERIODEField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string DOKUMENTART
    {
      get { return this.dOKUMENTARTField; }
      set { this.dOKUMENTARTField = value; }
    }

    /// <remarks/>
    public string NR
    {
      get { return this.nrField; }
      set { this.nrField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NMTOKEN")]
    public string DATUM
    {
      get { return this.dATUMField; }
      set { this.dATUMField = value; }
    }

    /// <remarks/>
    public string TITEL
    {
      get { return this.tITELField; }
      set { this.tITELField = value; }
    }

    /// <remarks/>
    public string TEXT
    {
      get { return this.tEXTField; }
      set { this.tEXTField = value; }
    }
  }
}